// import 'package:flutter/material.dart';

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(body: ListView(children: [Android()])),
//     );
//   }
// }

// class Android extends StatelessWidget {
//   const Android({super.key});
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 272,
//           height: 605,
//           clipBehavior: Clip.antiAlias,
//           decoration: BoxDecoration(color: Colors.white),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 0,
//                 top: 0,
//                 child: SizedBox(
//                   width: 272,
//                   height: 39,
//                   child: Row(
//                     mainAxisSize: MainAxisSize.min,
//                     mainAxisAlignment: MainAxisAlignment.start,
//                     crossAxisAlignment: CrossAxisAlignment.end,
//                     children: [
//                       Expanded(
//                         child: Container(
//                           height: 39,
//                           padding: const EdgeInsets.symmetric(
//                             horizontal: 15.60,
//                           ),
//                           child: Stack(
//                             children: [
//                               SizedBox(
//                                 width: 124.80,
//                                 height: double.infinity,
//                                 child: Row(
//                                   mainAxisSize: MainAxisSize.min,
//                                   mainAxisAlignment: MainAxisAlignment.start,
//                                   crossAxisAlignment: CrossAxisAlignment.center,
//                                   spacing: 7.80,
//                                   children: [
//                                     Text(
//                                       '9:30',
//                                       style: TextStyle(
//                                         color: const Color(
//                                           0xFF171D1B,
//                                         ) /* Schemes-On-Surface */,
//                                         fontSize: 13.65,
//                                         fontFamily: 'Roboto',
//                                         fontWeight: FontWeight.w400,
//                                         height: 1.43,
//                                         letterSpacing: 0.24,
//                                       ),
//                                     ),
//                                   ],
//                                 ),
//                               ),
//                               Row(
//                                 mainAxisSize: MainAxisSize.min,
//                                 mainAxisAlignment: MainAxisAlignment.end,
//                                 crossAxisAlignment: CrossAxisAlignment.center,
//                                 children: [
//                                   Row(
//                                     mainAxisSize: MainAxisSize.min,
//                                     mainAxisAlignment: MainAxisAlignment.start,
//                                     crossAxisAlignment:
//                                         CrossAxisAlignment.start,
//                                     children: [
//                                       Container(
//                                         width: 15.60,
//                                         height: 15.60,
//                                         clipBehavior: Clip.antiAlias,
//                                         decoration: BoxDecoration(),
//                                         child: Stack(),
//                                       ),
//                                       Container(
//                                         width: 15.60,
//                                         height: 15.60,
//                                         clipBehavior: Clip.antiAlias,
//                                         decoration: BoxDecoration(),
//                                         child: Stack(),
//                                       ),
//                                     ],
//                                   ),
//                                   SizedBox(
//                                     height: 50.70,
//                                     child: Row(
//                                       mainAxisSize: MainAxisSize.min,
//                                       mainAxisAlignment:
//                                           MainAxisAlignment.start,
//                                       crossAxisAlignment:
//                                           CrossAxisAlignment.center,
//                                       spacing: 1.95,
//                                       children: [
//                                         Container(
//                                           width: 15.60,
//                                           height: 15.60,
//                                           clipBehavior: Clip.antiAlias,
//                                           decoration: BoxDecoration(),
//                                           child: Stack(),
//                                         ),
//                                       ],
//                                     ),
//                                   ),
//                                 ],
//                               ),
//                               Positioned(
//                                 left: 124.15,
//                                 top: 7.80,
//                                 child: SizedBox(
//                                   width: 23.40,
//                                   height: 23.40,
//                                   child: Stack(
//                                     children: [
//                                       Positioned(
//                                         left: 0,
//                                         top: 0,
//                                         child: Container(
//                                           width: 23.40,
//                                           height: 23.40,
//                                           decoration: ShapeDecoration(
//                                             color: const Color(
//                                               0xFF2E2E2E,
//                                             ) /* Camera */,
//                                             shape: RoundedRectangleBorder(
//                                               borderRadius:
//                                                   BorderRadius.circular(97.50),
//                                             ),
//                                           ),
//                                         ),
//                                       ),
//                                     ],
//                                   ),
//                                 ),
//                               ),
//                             ],
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 18,
//                 top: 83,
//                 child: Container(
//                   width: 249,
//                   height: 187,
//                   decoration: ShapeDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/249x187"),
//                       fit: BoxFit.cover,
//                     ),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(96),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 94,
//                 top: 67,
//                 child: SizedBox(
//                   width: 92,
//                   height: 33,
//                   child: Text(
//                     'TEMUIN',
//                     style: TextStyle(
//                       color: Colors.black,
//                       fontSize: 24,
//                       fontFamily: 'Roboto',
//                       fontWeight: FontWeight.w400,
//                       height: 0.81,
//                       letterSpacing: 0.24,
//                     ),
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }
